models:
  - name: customers_stg
    description: Staged customer data from order management system (OMS), with minor row-level transformation.
    columns:
      - name: Email
        description: Customer's Primary Email address for promotions and offers.
        tests:
          - string_not_empty

 
  - name: orders_stg
    columns:
      - name: OrderID
        description: The primary key for orders_stg table
        tests:
          - unique
          - not_null

      - name: StatusCD
        description: "{{ doc('StatusCD') }}"
        tests:
          - accepted_values:
              values: ['01','02','03']

  - name: orderitems_stg
    description: Staged order items data from order management system (OMS), with minor row-level transformation.
    columns:
      - name: OrderID
        tests:
          - relationships:
              to: ref('orders_stg')
              field: OrderID
